version: '3'

services:
  backend:
    build: ./container/backend/
    container_name: dataloader-backend
    tty: true
    ports:
      - ${BACKEND_PORT}:4000
    volumes:
      - ./backend:/app/backend
    working_dir: "/app/backend"
    # command: sh -c "npm i; npm start;"
    depends_on:
      - mysql
    entrypoint: >-
      sh -c "
        if [ ! -e '/app/node_modules/graphql' ]; then
          npm install
        fi
        npm run start
      "
  mysql:
    image: mysql:8.0
    container_name: dataloader-mysql
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./container/mysql/conf.d:/etc/mysql/conf.d
      - ./container/mysql/data:/var/lib/mysql
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: dataloader
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  